export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"

export const TOP_PRODUCTS_SUCCESS = "TOP_PRODUCTS_SUCCESS"
export const TOP_PRODUCTS_FAIL = "TOP_PRODUCTS_FAIL"
export const TOP_PRODUCTS_REQUEST = "TOP_PRODUCTS_REQUEST"

export const PRODUCT_DETAILS_SUCCESS= "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const CLEAR_PRODUCT_DETAILS = "CLEAR_PRODUCT_DETAILS"

export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"
export const USER_DETAILS_RESET = "USER_DETAILS_RESET"

export const SAVE_ADDRESS = "SAVE_ADDRESS"
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD"

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST"
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS"
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL"
export const MY_ORDERS_RESET = "MY_ORDERS_RESET"

export const PRODUCT_CREATE_REVIEW_SUCCESS= "PRODUCT_CREATE_REVIEW_SUCCESS"
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL"
export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST"
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET"